### PR TITLE
Support for UTF-8 and extra data types

### PR DESCRIPTION
**Pull request by dlorson**
I've added some minor improvements + tests:
- Chunk lengths now take multibyte characters into account
- Added the STRING, CLOB, BOOLEAN data types.

### CODE REVIEW

**Comment by archan937** [comment]
Hey Dennis,

Thanks for the pull request. Unfortunately I see that some tests are failing. Could you please resolve this first?

Greets,
Paul.

**Comment by dlorson** [comment]
Ruby 1.9 needed some extra care.  Everything running smoothly now!

**Comment by archan937** [comment]
Thanks, Dennis!

https://github.com/archan937/monetdb/blob/master/CHANGELOG.rdoc#version-029-july-3-2015

**Comment by dlorson** [comment]
Great, thanks!  It's just some small stuff, but glad I could help.

**Comment by archan937** [comment]
Cheers

**Pull request merged**
